project/InformationSystem/InformationSystem/Controllers/SearchController.cs
using InformationSystem.Data.Models;
using InformationSystem.ViewModels.Mentors;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using InformationSystem.Data;
using Microsoft.AspNetCore.Mvc.Rendering;
using InformationSystem.Data.Models.SkillsAndEducation;
using System.Linq;
using InformationSystem.Data.Models.Project;
using NuGet.Packaging.Signing;
using NuGet.Packaging;
using InformationSystem.Data.TagHelpers;
using Microsoft.EntityFrameworkCore;

namespace InformationSystem.Controllers
{
    public class SearchController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private readonly ApplicationDbContext _context;

        public SearchController(ApplicationDbContext context, UserManager<User> userManager, SignInManager<User> signInManager)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;

        }

        public async Task<IActionResult> IndexAsync(string? SearchEmail, 
                                   string? SearchFamily, 
                                   string? SearchName,
                                   int[]? SearchCourseId,
                                   int[]? SearchProjectId,
                                   List<int?> SearchSoftId,
                                   List<int?> SearchHardId,
                                   List<int?> SearchSoftLevel,
                                   List<int?> SearchHardLevel,
                                   int page = 1)
        {

            var user = await _userManager.GetUserAsync(User); if (user == null) return RedirectToAction("Login", "Account");
            var userId = user.Id;

            List<User> allUsers = _userManager.Users.Where(p => p.isActive != false).ToList();
            allUsers.Remove(user);

            //фильтры
            try
            {
                if (SearchEmail != null)
                {
                    allUsers = (List<User>)allUsers.Where(x => x.Email.Contains(SearchEmail)).ToList();
                    ViewBag.SearchEmail = SearchEmail;
                }

                if (SearchFamily != null)
                {
                    allUsers = (List<User>)allUsers.Where(x => x.Surname.Contains(SearchFamily)).ToList();
                    ViewBag.SearchFamily = SearchFamily;
                }

                if (SearchName != null)
                {
                    allUsers = (List<User>)allUsers.Where(x => x.Name.Contains(SearchName)).ToList();
                    ViewBag.SearchName = SearchName;
                }

                if (SearchCourseId.Length > 0)
                {
                    List<EducationList> getUsersCourse = _context.educationList.Where(p => SearchCourseId.Any(g => p.EducationId == g)).ToList();

                    allUsers = (List<User>)allUsers.Where(p => getUsersCourse.Any(g => p.Id == g.EmployeeId)).ToList();

                }


                if (SearchProjectId.Length > 0)
                {
                    //List<ProjectList> getUsersProject = _context.projectList.Where(p => SearchProjectId.Any(g => p.ProjectsId == g)).ToList();
                    
                    List<ProjectList> getUsersProject = _context.projectList.Where(p => SearchProjectId.Any(g => (int)p.ProjectsId == g)).ToList();

                    allUsers = (List<User>)allUsers.Where(p => getUsersProject.Any(g => p.Id == g.EmployeeId)).ToList();
                }

                if (SearchSoftId.FindAll(c => c != null).Count > 0)
                {
                    List<SoftSkillsList> getUsersSoft = new List<SoftSkillsList>();
                    List<SoftSkillsList> getUsersSoftTemp = null;

                    //getUsersSoft = _context.softSkillsList.Where(p => SearchSoftId.(g => p.SoftSkillsId == g) && SearchSoftLevel.Any(h => p.CompetenceLevelId == h)).ToList();
                    var SoftSkillsAndLevels = SearchSoftId.Zip(SearchSoftLevel, (s, l) => new { Skill = s, Level = l }).ToList();
                    int i = 0;
                   // getUsersSoft = _context.softSkillsList.Where(p => p.SoftSkillsId == ).ToList();
                    foreach (var softListItem in SoftSkillsAndLevels)
                        if (softListItem.Skill != null)
                            if (softListItem.Level != null)
                            { 
                                getUsersSoftTemp = _context.softSkillsList.Where(p => p.SoftSkillsId == softListItem.Skill && p.CompetenceLevelId == softListItem.Level).ToList();                                
                                if (getUsersSoftTemp.Count == 0)
                                    i++;
                                else
                                    getUsersSoft.AddRange(getUsersSoftTemp);
                            }                               
                            else
                            {
                                getUsersSoftTemp = _context.softSkillsList.Where(p => p.SoftSkillsId == softListItem.Skill).ToList();                                
                                if (getUsersSoftTemp.Count == 0)
                                    i++;
                                else
                                    getUsersSoft.AddRange(getUsersSoftTemp);
                            }

                    if(i > 0)
                        getUsersSoft = new List<SoftSkillsList>();
                    allUsers = (List<User>)allUsers.Where(p => getUsersSoft.Any(g => p.Id == g.EmployeeId)).ToList();
                }

                if (SearchHardId.FindAll(c => c != null).Count > 0)
                {
                    List<HardSkillsList> getUsersHard = new List<HardSkillsList>(); ;
                    List<HardSkillsList> getUsersHardTemp = null;

                    var HardSkillsAndLevels = SearchHardId.Zip(SearchHardLevel, (s, l) => new { Skill = s, Level = l });
                    int i = 0;
                    foreach (var hardListItem in HardSkillsAndLevels)
                        if (hardListItem.Skill != null)
                            if (hardListItem.Level != null)
                            {
                                getUsersHardTemp = _context.hardSkillsList.Where(p => p.HardSkillsId == hardListItem.Skill && p.CompetenceLevelId == hardListItem.Level).ToList();
                                if (getUsersHardTemp.Count == 0)
                                    i++;
                                else
                                    getUsersHard.AddRange(getUsersHardTemp);
                            }
                            else
                            {
                                getUsersHardTemp = _context.hardSkillsList.Where(p => p.HardSkillsId == hardListItem.Skill).ToList();
                                if (getUsersHardTemp.Count == 0)
                                    i++;
                                else
                                    getUsersHard.AddRange(getUsersHardTemp);
                            }

                    if (i > 0)
                        getUsersHard = new List<HardSkillsList>();
                    allUsers = (List<User>)allUsers.Where(p => getUsersHard.Any(g => p.Id == g.EmployeeId)).ToList();
                }   
            }
            catch (Exception)
            {
                ViewBag.SearchEmail = null;
                ViewBag.SearchFamily = null;
                ViewBag.SearchName = null;
            }

            bool isAdmin = User.IsInRole("Admin");
            bool isManager = User.IsInRole("Manager");

            //добавление кнопок пользователям
            List<AllUsersViewModel> allUsersView = new List<AllUsersViewModel>();
            foreach (var item in allUsers)
            {
                AllUsersViewModel buf = new AllUsersViewModel();
                buf.Surname = item.Surname;
                buf.Name = item.Name;
                buf.Email = item.Email;

                if (_context.mentors.Where(p => p.TraineeId == userId && p.TraineeConfirmed == true && p.MentorId == item.Id).Count() > 0)
                {
                    buf.showMentorButton = false;
                }
                else { buf.showMentorButton = true; }

                if (_context.mentors.Where(p => p.MentorId == userId && p.MentorConfirmed == true && p.TraineeId == item.Id).Count() > 0)
                {
                    buf.showTraineeButton = false;
                }
                else { 
                    buf.showTraineeButton = true; 
                }

                buf.showProfileButton = false;
                if (isAdmin || isManager)
                {
                    buf.showProfileButton = true;
                }
                //проверка наставника
                else if (_context.mentors.Where(p => p.MentorId == user.Id && p.TraineeId == userId
                                                        && p.TraineeConfirmed == true && p.MentorConfirmed == true).Any() == true)
                {
                    buf.showProfileButton = true;
                }


                allUsersView.Add(buf);
            }

            //передача данных для фильтров
            ViewBag.Courses = new MultiSelectList(_context.education.Where(p => p.CourseName != string.Empty), "EducationId", "CourseName", SearchCourseId.ToList());
            ViewBag.Projects = new MultiSelectList(_context.projects.Where(p => p.Name != string.Empty), "Id", "Name", SearchProjectId.ToList());
            ViewBag.SoftSkills = new SelectList(_context.softSkills.Where(p => p.CompetencyName != string.Empty), "SoftSkillsId", "CompetencyName");
            ViewBag.SoftLevels = new SelectList(_context.competenceLevel.Where(p => p.Level != string.Empty), "CompetenceLevelId", "Level");

project/InformationSystem/InformationSystem/Views/Search/Index.cshtml
@using static InformationSystem.Controllers.SearchController;
@model SearchViewModel

@{
    ViewData["Title"] = "Поиск сотрудника";
}

<link href="~/multiselect/example-styles.css" rel="stylesheet" />

<div class="container">
    <div class="row">
        @*Фильтры*@
        <div class="col-3">
            <h2>Фильтры</h2>
            <form asp-controller="Search" asp-action="Index">
                <div class="form-group">
                    <label class="control-label">Фамилия: </label>
                    <input class="form-control" name="SearchFamily" value="@ViewBag.SearchFamily" />
                </div>

                <div class="form-group">
                    <label class="control-label">Имя: </label>
                    <input class="form-control" name="SearchName" value="@ViewBag.SearchName" />
                </div>

                <div class="form-group">
                    <label class="control-label">Email: </label>
                    <input class="form-control" type="text" name="SearchEmail" value="@ViewBag.SearchEmail" />
                </div>

                <div class="form-group">
                    <label class="control-label">Курсы: </label>
                    <select id="dropDownList-course" name="SearchCourseId"
                            asp-items="@ViewBag.Courses" multiple class="form-control"></select>
                </div>

                <div class="form-group">
                    <label class="control-label">Проекты: </label>
                    <select id="dropDownList-project" name="SearchProjectId"
                            asp-items="@ViewBag.Projects" multiple class="form-control"></select>
                </div>

                <div class="form-group" id="SoftList">
                    <label class="control-label">Soft Навыки</label>
                    <select name="SearchSoftId" asp-items="@ViewBag.SoftSkills" style="margin: 0.5rem 0.5rem;">
                        <option value="">--выберите качество--</option>
                    </select>
                    <select name="SearchSoftLevel" asp-items="@ViewBag.SoftLevels" style="width: 80px;">
                        <option value="">--уровень--</option>
                    </select>
                    <button id="SoftButton" class="btn btn-sm btn-secondary">Добавить</button>
                </div>

                <div class="form-group">
                    <label class="control-label">Hard Навыки</label><div></div>
                    <select name="SearchHardId" asp-items="@ViewBag.HardSkills" style="margin: 0.5rem 0.5rem;">
                        <option value="">--выберите навык--&nbsp;&nbsp;&nbsp;&nbsp;</option>
                    </select>
                    <select name="SearchHardLevel" asp-items="@ViewBag.HardLevels" style="width: 80px;">
                        <option value="">--уровень--</option>
                    </select>
                    <button id="HardButton" class="btn btn-sm btn-secondary">Добавить</button>
                </div>

                <div class="d-grid gap-2">
                    <button type="submit" style="margin: 5px;" class="btn btn-primary justify-content-center">Поиск</button>
                </div>
            </form>
        </div>
        @*Список пользователей*@
        <div class="col-9">
            <h2>Список сотрудников</h2>
            @if (ViewBag.AllUsers.Count > 0)
            {
                <table class="table">
                    <tr>
                        <th>Фамилия</th>
                        <th>Имя</th>
                        <th>Email</th>
                    </tr>
                    @{
                        foreach (var item in Model.AllUsers)
                        {
                            <tr>
                                <td style="width: 15%;">@item.Surname</td>
                                <td style="width: 15%;">@item.Name</td>
                                <td style="width: 15%;">@item.Email</td>
                                <td style="width: 20%;">
                                    @if (item.showMentorButton == true)
                                    {
                                        <a style="width: 100%;" class="btn btn-sm btn-primary" asp-controller="Mentors" asp-action="AddMentor" asp-route-email="@item.Email" asp-route-search="@true">Добавить наставника</a>
                                    }
                                    else
                                    {
                                        <a style="width: 100%;" class="btn btn-sm btn-danger" asp-controller="Mentors" asp-action="RemoveMentor" asp-route-email="@item.Email" asp-route-search="@true">Удалить наставника</a>
                                    }

                                </td>
                                <td style="width: 20%;">
                                    @if (item.showTraineeButton == true)
                                    {
                                        <a style="width: 100%;" class="btn btn-sm btn-primary" asp-controller="Mentors" asp-action="AddTrainee" asp-route-email="@item.Email" asp-route-search="@true">Добавить подопечного</a>
                                    }
                                    else
                                    {
                                        <a style="width: 100%;" class="btn btn-sm btn-danger" asp-controller="Mentors" asp-action="RemoveTrainee" asp-route-email="@item.Email" asp-route-search="@true">Удалить подопечного</a>
                                    }
                                </td>
                                <td style="width: 10%;">
                                    @if (item.showProfileButton == true)
                                    {
                                        <a style="width: 100%;" class="btn btn-sm btn-primary" asp-controller="profile" asp-action="profileview" asp-route-email="@item.Email">Перейти</a>
                                    }
                                </td>
                            </tr>
                        }
                    }
                </table>
                @if (Model.PageViewModel.HasPreviousPage)
                {
                    <a asp-action="Index"
               asp-route-page="@(Model.PageViewModel.PageNumber - 1)"
                       class="btn btn-outline-dark">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                        Назад
                    </a>
                }
                @if (Model.PageViewModel.HasNextPage)
                {
                    <a asp-action="Index"
               asp-route-page="@(Model.PageViewModel.PageNumber + 1)"
                       class="btn btn-outline-dark">
                        Вперед
                        <i class="glyphicon glyphicon-chevron-right"></i>
                    </a>
                }
            }
            else
            {
                <div class="container">
                    <h4 style="text-align: center">Странно, но ничего нет</h4>
                    <h5 style="text-align: center">Попробуйте изменить критерии поиска</h5>
                </div>
            }
        </div>
    </div>
</div>

@section Scripts{
    <script src="~/multiselect/jquery.multi-select.js"></script>
    <script>
        $(document).ready(function () {
            $('#dropDownList-course').multiSelect();
        });

        $(document).ready(function () {
            $('#dropDownList-project').multiSelect();
        });
    </script>
}

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {

        $("#SoftButton").click(function (e) {
            e.preventDefault();
            var rowCount = $('[name="SearchSoftId"]').length;
            $('[name="SearchSoftLevel"]').last().after($('select[name="SearchSoftId"]').last().clone());
            $('[name="SearchSoftId"]').last().after($('select[name="SearchSoftLevel"]').last().clone());
        });

        $("#HardButton").click(function (e) {
            e.preventDefault();
            var rowCount = $('[name="SearchHardId"]').length;
            $('[name="SearchHardLevel"]').last().after($('select[name="SearchHardId"]').last().clone());
            $('[name="SearchHardId"]').last().after($('select[name="SearchHardLevel"]').last().clone());
        });
    });
</script>

<style>
    .multi-select-button {
        min-width: 200px;
    }

.card-body{
        padding: 0.5rem 0.5rem;
}    
</style>

<style>
    @@font-face {
        font-family: 'FontAwesome';
        src: url('https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/fonts/fontawesome-webfont.woff2') format('woff2'), url('https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/fonts/fontawesome-webfont.woff') format('woff'), url('https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/fonts/fontawesome-webfont.ttf') format('truetype');
        font-weight: normal;
        font-style: normal
    }

    .glyphicon {
        display: inline-block;
        font: normal normal normal 14px/1 FontAwesome;
        font-size: inherit;
        text-rendering: auto;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale
    }

    .glyphicon-chevron-right:before {
        content: "\f054";
    }

    .glyphicon-chevron-left:before {
        content: "\f053";
    }
</style>